export type ClientOverview = {
  id: string;
  org_id: string;
  name: string;
  email: string | null;
  phone: string | null;
  company: string | null;
  status: 'Lead' | 'Prospect' | 'Active' | 'Past';
  tags: string[];
  created_at: string;
  website_url: string | null;
  ga4_property_id: string | null;
  vercel_project_id: string | null;
  total_invoiced_cents: number;
  total_paid_cents: number;
  balance_due_cents: number;
  draft_invoiced_cents: number;
  current_stage: 'Contacted' | 'Negotiation' | 'Contract Sent' | 'Contract Signed' | 'Won' | 'Lost' | 'Abandoned' | null;
  last_activity_at: string | null;
};
