name: Run Business Automations

on:
  schedule:
    # Run email sequences at 9 AM EST daily
    - cron: '0 14 * * *'  # 14:00 UTC = 9:00 AM EST
    # Run invoice follow-ups at 8 AM EST daily
    - cron: '0 13 * * *'  # 13:00 UTC = 8:00 AM EST
  workflow_dispatch: # Allow manual triggers

jobs:
  email-sequences:
    runs-on: ubuntu-latest
    steps:
      - name: Process Email Sequences
        run: |
          curl -X POST "https://www.nunezdev.com/api/cron/process-email-sequences" \
            -H "Authorization: Bearer e9cb95b03a35b837a8437d21c133272d2d0f32abda366a90c8614fbcd342b677" \
            -H "Content-Type: application/json" \
            --max-time 30 \
            --retry 3

  invoice-followups:
    runs-on: ubuntu-latest
    steps:
      - name: Process Invoice Follow-ups
        run: |
          curl -X POST "https://www.nunezdev.com/api/cron/process-invoice-followups" \
            -H "Authorization: Bearer e9cb95b03a35b837a8437d21c133272d2d0f32abda366a90c8614fbcd342b677" \
            -H "Content-Type: application/json" \
            --max-time 30 \
            --retry 3